[workspace]
resolver = "2"
default-members = [
    "explora",
]
members = [
    "explora",
    "common",
    "render",
    "server",
    "server-cli"
]

[workspace.dependencies]
log = "0.4.20"
vek = "0.16.1"