[workspace]
resolver = "2"
default-members = [
    "explora",
]
members = [
    "common",
    "explora",
    "server",
    "server-cli"
]

[workspace.dependencies]
log = "0.4.20"
vek = "0.16.1"
apecs = "0.7.0"
serde = "1.0.195"
toml = "0.8.8"
noise = "0.8.2"
bincode = "1.3.3"