[package]
name = "explora_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apecs = "0.7.0"
log = { workspace = true }
vek = { workspace = true }