[package]
name = "explora_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apecs = { workspace = true }
log = { workspace = true }
noise = "0.8.2"
rand = "0.8.5"
vek = { workspace = true }
